import guan

# test
guan.test()

# Pauli matrix
sigma_0 = guan.sigma_0()
sigma_x = guan.sigma_x()
sigma_y = guan.sigma_y()
sigma_z = guan.sigma_z()
sigma_00 = guan.sigma_00()
sigma_0x = guan.sigma_0x()
sigma_0y = guan.sigma_0y()
sigma_0z = guan.sigma_0z()
sigma_x0 = guan.sigma_x0()
sigma_xx = guan.sigma_xx()
sigma_xy = guan.sigma_xy()
sigma_xz = guan.sigma_xz()
sigma_y0 = guan.sigma_y0()
sigma_yx = guan.sigma_yx()
sigma_yy = guan.sigma_yy()
sigma_yz = guan.sigma_yz()
sigma_z0 = guan.sigma_z0()
sigma_zx = guan.sigma_zx()
sigma_zy = guan.sigma_zy()
sigma_zz = guan.sigma_zz()
print('Pauli matrix\n')
print('sigma_0\n', sigma_0, '\n')
print('sigma_x\n', sigma_x, '\n')
print('sigma_y\n', sigma_y, '\n')
print('sigma_z\n', sigma_z, '\n')
print('sigma_00\n', sigma_00, '\n')
print('sigma_0x\n', sigma_0x, '\n')
print('sigma_0y\n', sigma_0y, '\n')
print('sigma_0z\n', sigma_0z, '\n')
print('sigma_x0\n', sigma_x0, '\n')
print('sigma_xx\n', sigma_xx, '\n')
print('sigma_xy\n', sigma_xy, '\n')
print('sigma_xz\n', sigma_xz, '\n')
print('sigma_y0\n', sigma_y0, '\n')
print('sigma_yx\n', sigma_yx, '\n')
print('sigma_yy\n', sigma_yy, '\n')
print('sigma_yz\n', sigma_yz, '\n')
print('sigma_z0\n', sigma_z0, '\n')
print('sigma_zx\n', sigma_zx, '\n')
print('sigma_zy\n', sigma_zy, '\n')
print('sigma_zz\n', sigma_zz, '\n')